sonar.projectKey=saswath123_sonar
sonar.organization=saswath123
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
